<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The ledger of subscription reminders already sent.
 *
 * The legacy site had a table shaped for this — `email_send` (job, customer,
 * date) — and never wrote a row to it. Its expired notice simply mailed every
 * lapsed carrier each time the endpoint was hit, because a reminder is
 * generated by a schedule rather than by a user action and nothing else stops
 * it going out again. That is how a helpful reminder turns into the thing
 * people filter.
 *
 * The unique index is the actual guard, not the SELECT that precedes it. Two
 * overlapping runs — a cron that ran long and the next one starting — both see
 * "not sent yet" and both send. Here the second INSERT fails at the database
 * and that send is skipped, so at most one message exists per milestone no
 * matter how the schedule misbehaves.
 *
 * This is also the admin record of who was reminded and when, so it keeps the
 * rows for milestones that were deliberately *not* emailed (`sent_at` null,
 * with a reason) rather than only the ones that were. A carrier asking "why
 * did I never hear from you" is answered by a row either way.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('subscription_reminders', function (Blueprint $table) {
            $table->id();
            $table->foreignId('subscription_id')->constrained()->cascadeOnDelete();

            // Denormalised so the admin list can filter and sort by carrier
            // without joining through subscriptions, and so the record
            // survives as history if the subscription row is ever reworked.
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();

            // 'expiring' before the end date, 'expired' after it.
            $table->string('kind', 16);

            /*
             * Which point in the cadence this is — a label, not a day count,
             * because the schedule mixes fixed days with calendar months and
             * months are not a fixed number of days:
             *
             *   expiring : d5, d3, d1        (days before the end date)
             *   expired  : d3, d7, d15       (days after it)
             *              m1, m2, m3, ...   (monthly from the end date)
             *
             * Part of the unique key, so every milestone is its own send and
             * an early one cannot block a later one.
             */
            $table->string('milestone', 16);

            // Null means the milestone was recorded without emailing. That
            // happens on the first sweep over a long-lapsed subscription,
            // where the backlog is suppressed and only the newest milestone
            // is actually sent. `skip_reason` says which.
            $table->timestamp('sent_at')->nullable();
            $table->string('skip_reason', 32)->nullable();

            $table->timestamps();

            $table->unique(['subscription_id', 'kind', 'milestone'], 'subscription_reminders_unique');

            // The admin list: newest first, and per-carrier history.
            $table->index(['sent_at']);
            $table->index(['user_id', 'sent_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('subscription_reminders');
    }
};
